---
title: "all country results in a single data file"
author: "Gregory Guranich"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{all country}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(FPEMcountry)
devtools::load_all()
library(ggplot2)
library(grid)
library(gridExtra)
```

# Set output directory and divs for the set of results
```{r}
aven_data <- readr::read_csv("C:/Users/desktop-g/Downloads/Track20Database033020.csv") # read in data
divs <- aven_data %>% dplyr::pull(division_numeric_code) %>% unique() %>% as.list() # make a list of division codes from your data
purrr::pmap(
  list(
    runname = divs,
    division_numeric_code = divs,
    surveydata_filepath = "C:/Users/desktop-g/Downloads/Track20Database033020.csv",
    is_in_union = "ALL",
    first_year = 1970,
    last_year = 2030
  ),
  fit_fp_c_autosave # the fit function we are mapping too 
)
# divs <- divs[191:196] # remaining subset after error
purrr::pmap(
  list(runname = divs),
  calc_fp_c_autosave # the fit function we are mapping too 
)

# country code 580 failed since there is no package pop counts for that country,

# #error at 189
# # for div 520,
# # check the fit to see if samples exist for unmarried, N,
# temp <- readRDS(paste0("output/runs/", 580, ".rds"))
# temp <- readRDS(paste0("output/results/", 580, ".rds"))
# # ok so it was the country after 520
# divs[190]
# temp <- 
# getwd()
# temp <- FPEMcountry::fit_fp_c(
#     surveydata_filepath = "C:/Users/desktop-g/Downloads/Track20Database033020.csv",
#     division_numeric_code = 580,
#     is_in_union = "ALL",
#     first_year = 1970,
#     last_year = 2030
# )
# temp2 <- FPEMcountry::calc_fp_c(temp)
# 
# # can we fit a model with no data?
```

```{r}
# divs <- divs[-190]
unions <- c("Y", "N", "ALL")

allreslist <- list()
for (div in divs) {
  fits <- readRDS(paste0("output/runs/", div, ".rds"))
  results <- readRDS(paste0("output/results/", div, ".rds"))
  union_reslist <- list()
  for (union in c("Y", "N", "ALL")) {
    result <- results %>% purrr::pluck(union)
    fit <- fits %>% purrr::pluck(union)
    union_reslist[[union]] <- data.frame(
              name_country = fit$core_data$units$name_country,
              division_numeric_code = fit$core_data$units$division_numeric_code,
              is_in_union = union,
              year = result$contraceptive_use_any$year ,
              percentile = result$contraceptive_use_any$percentile,
              contraceptive_use_any = result$contraceptive_use_any$value,
              contraceptive_use_modern = result$contraceptive_use_modern$value,
              contraceptive_use_traditional = result$contraceptive_use_traditional$value,
              unmet_need_any = result$unmet_need_any$value,
              unmet_need_modern = result$unmet_need_modern$value,
              demand_satisfied_modern = result$demand_satisfied_modern$value
        )
  }
  # rbind across the list
  allreslist[[div]] <- do.call(rbind, union_reslist)
}
df <- do.call(rbind, allreslist)
write.csv(df, "avenir_fp_results_070320.csv")
```



